name: ci action

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: git pull
        uses: actions/checkout@v4
        with:
          ref: master

      - name: install QEMU
        uses: docker/setup-qemu-action@v3

      - name: install buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: rosven9856
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push docker container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            rosven9856/php:${{ github.event.release.tag_name }}
            rosven9856/php:latest

      - name: create release in rosven9856/php-extended-docker repository
        env:
          GH_TOKEN: ${{ secrets._GITHUB_TOKEN }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/rosven9856/php-extended-docker/releases \
            -f tag_name='${{ github.event.release.tag_name }}' \
            -f target_commitish='master' \
            -f name='${{ github.event.release.tag_name }}' \
            -f body='' \
            -F draft=false \
            -F prerelease=false \
            -F generate_release_notes=false

      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Github. Creating new release php
            
            Repository: ${{ github.repository }}
            Release: ${{ github.event.release.tag_name }}

            See details: https://github.com/${{ github.repository }}/releases